# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29e1086c8ff3090062f6b43b0812d3b863a2194ae7780597a30758de325c5ff87ef182285b513cc3831de6a712e3faed4e48b1b5eb49e0ec7263521ed7a56e67

test:
  secret_key_base: 225a0426baa52433e404013ef27cc0d33a4b78ca1b4a2b459fe46381b1367f3b1afbbfebfea95199224203ae27eaea36a8ee8ad804a74a57911752f802c501dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
